### ISSUE TITLE
Incompatibility with Java 8

### ISSUE THREAD

**Issue by vladimir-filipchanka** [std-uritemplate/std-uritemplate#132]
After bumping kiota deps to `1.0.3` (see https://github.com/microsoftgraph/msgraph-sdk-java/issues/1831
for more context) with the latest release `6.2.1` at the day of writing, I was able to get a bit further. 
But the next hump is 

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/github/stduritemplate/StdUriTemplate has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at com.microsoft.kiota.RequestInformation.getUri(RequestInformation.java:125)
	at com.microsoft.kiota.authentication.BaseBearerTokenAuthenticationProvider.authenticateRequest(BaseBearerTokenAuthenticationProvider.java:41)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.getHttpResponseMessage(OkHttpRequestAdapter.java:709)
	at com.microsoft.kiota.http.OkHttpRequestAdapter.send(OkHttpRequestAdapter.java:274)
	at com.microsoft.graph.serviceprincipals.item.ServicePrincipalItemRequestBuilder.patch(ServicePrincipalItemRequestBuilder.java:358)
	at com.microsoft.graph.serviceprincipals.item.ServicePrincipalItemRequestBuilder.patch(ServicePrincipalItemRequestBuilder.java:343)
```

Github's [stduritemplate lib](https://github.com/std-uritemplate/std-uritemplate) is not compatible with java 8. It is transitive dep through `com.microsoft.kiota:microsoft-kiota-abstractions`. 
The thing is stduritemplate doesn't seem to ever had a compatibility with Java 8, as 0.0.1 [version](https://github.com/std-uritemplate/std-uritemplate/blob/0.0.1/java/pom.xml#L37) had `maven.compiler.source = 11` right away

**Comment by vladimir-filipchanka** [comment]
Thanks for your reply, @andreaTP 

I don't think we have a specific requirements for Java 8, it's just where we are right now. Moving to something newer would be a great idea, but I don't think it's something on the roadmap now. 

It might make more sense to reach out to [msgraph-sdk-java](https://github.com/microsoftgraph/msgraph-sdk-java) supporters and ask this question as they claim that the project Java 8+.

**Comment by baywet** [comment]
@andreaTP chiming in here.
As far as I understand android runtimes are effectively a tweaked version of java 8 + a bunch of updates. Wouldn't we lose compatibility for those scenarios by keeping the bar higher?
Also, while I agree it's an older release, are we using anything here that requires anything more than java 8? Would there be any drawbacks? (perf, maintenance...)

**Comment by andreaTP** [comment]
> As far as I understand android runtimes are effectively a tweaked version of java 8 + a bunch of updates. Wouldn't we lose compatibility for those scenarios by keeping the bar higher?

I have to admit that my understanding of Android is pretty limited, from what I see Java 11 is mostly supported (especially for syntax things like we are using here).

> Also, while I agree it's an older release, are we using anything here that requires anything more than java 8? Would there be any drawbacks? (perf, maintenance...)

To evaluate the effort I almost did it here: https://github.com/std-uritemplate/std-uritemplate/commit/c88c93a08aff805b40a67cc0f32f49f2ba5040bf (Unicode characters handling is still not working but haven't spent enough time on it).
From Java 8+ we are using two things:
 - `var`: that's just syntactic sugar
 - a few methods for encoding/decoding in a safe way
 
 I don't see any hit on performance, maintenance wise we might start to get issues when upgrading the tooling, but that's not the case just yet.
 
 All in all, I would prefer to avoid maintaining Java 8, but I'm open to feedback from Android developers and I would merge a PR if it's small and maintainable enough.

**Comment by baywet** [comment]
Thanks for re-opening, and for the additional context.
From what I understand from [this documentation page](https://developer.android.com/build/jdks) :
- the source version is driven by sourceCompatibility of the project
- the binary version is driven by the targetCompatibility of the project

The ranges you can use for those two is driven by the compile (android) SDK version set in the project.

And that maps to the Android versions one wants to support.

In my experience most Android developers will target SDK version 19 or at most 21 / android 5 lolipop  (that's from when I was only working on the Microsoft Graph Java SDK > ~3 years ago now, targets probably have changed since) unless they really need something from the new APIs. And when a library forces developers to drop market share, they get really grumpy.

A couple of interesting aspects as I'm firing a dusty android studio:
- the default API version that's suggested is now 24 with about 97% of market share.
- the lowest available API version is now 21 (used to be 17 back in the days), most likely because older version don't even get security updates anymore.

Now, if we look at that from a consistency perspective, and coming from kiota:
- we made sure that kiota java dependencies are java 8 compatible (in fact you helped a great deal with that!)
- we made sure kiota generates java 8 source
- all other dependencies brought on by kiota java implementations (ok http, gson,...) are java 8 compatible

It seems to me a bit inconsistent that we have a single dependency (a really important one for that matter, and the only one that can't be replaced since it's brough on by abstractions) would break that compatibility.

What held you from wrapping up your commit back then?

**Comment by andreaTP** [comment]
Thanks for the additional context @baywet appreciated.

> older version don't even get security updates anymore.

That's correct, Java 8 is not even receiving security patches as of today.

All in all, in this project, is much easier/faster to just support it instead of arguing 😄 I finished up to work on my branch.

**Comment by andreaTP** [comment]
Release `0.0.54` is on its way to Maven Central, thanks everyone for the discussion!

**Comment by vladimir-filipchanka** [comment]
tested msgraph-sdk-java with new 0.0.54 and Java8. All good. Thank you for the effort!

**Comment by andreaTP** [comment]
Thanks for rising this up! 👍
