### ISSUE TITLE
RFC 3339 issue with date-time in GET request

### ISSUE THREAD

**Issue by pjmagee** [std-uritemplate/std-uritemplate#239]
Hello,

I think i found an issue with `std-uritemplate` for python, it's pretty breaking for us at the moment. our API requests an RFC 3339 date-time formatted query parameter. The concept is that we return an RFC 3339 date-time object from the API, kiota serialises that date-time into a datetime object and it is able to be passed back as a query parameter to an API Endpoint, however doing so is causing issues on RFC date-time validation on the server, because the `Z` should only occur when no time-zone is provided, according to the RFC 3339 Specificiation, this is also not being validated/deserialised correctly by Microsofts `System.Text.Json` feature to support deserialising RFC 3339 date-time strings. 

https://github.com/microsoft/kiota-abstractions-python/issues/352

Any thoughts on this?

**Comment by andreaTP** [comment]
Hi @pjmagee ! Thanks for taking the time to submit this issue!

The current implementation of RFC 3339 in Python is [not ideal](https://github.com/std-uritemplate/std-uritemplate/blob/f9355e33b8e8ed1bda9b9f85ff3b3b7d12279e0c/python/stduritemplate/__init__.py#L352), we probably should switch to something more [similar to Dart](https://github.com/std-uritemplate/std-uritemplate/blob/f9355e33b8e8ed1bda9b9f85ff3b3b7d12279e0c/dart/lib/std_uritemplate.dart#L16-L29), where we are doing something very similar to your proposal.

We should also have a test to verify the alternative code path in the `uritemplate-test-additional` folder.

Are you willing to send a PR to fix this one?

**Comment by andreaTP** [comment]
> Are you willing to send a PR to fix this one?

Looking at the issue more closely, the only way to test it is to update all the implementation test harnesses etc. etc.
I try to send a patch asap.

**Comment by andreaTP** [comment]
> Does that make sense?

Completely, and that's the conclusion reached in #240

**Comment by baywet** [comment]
I think we're facing some confusion here, let me try to clarify things a bit.
RFC 3339 defines [multiple parts](https://www.rfc-editor.org/rfc/rfc3339#section-5.6)
We can further cross check that [with the OAS format registry](https://spec.openapis.org/registry/format/) (I know those specs are "unrelated" at their core, but they built upon each other).

| name | example representation | OAS format | C# data type |
| ------ | --------- | --------------- | ---- |
| date-time | 2024-09-12T13:25:18+04:00 | date-time | DateTimeOffset |
| full-date | 2024-09-12 | date | DateOnly (6+) |
| full-time | 13:25:18+04:00 | time | TimeOnly (6+) |
| time-offset | +04:00 | N/A | TimeSpan |
| duration | P30M | duration | TimeSpan |
| period | 2024-09-12T13:25:18+04:00/30M | N/A | ??? |

[RFC 6570 variables](https://www.rfc-editor.org/rfc/rfc6570#section-3.2.1) have no notion of a variable type from reading the spec, looking at the examples etc... beyond "array", "object", "string".

Handling the "serialization" of anything other than a string value is a nice thing to do here, but could be a slippery slope. We should only do so if we have a clear mapping of a specific data type to a given representation, and that type contains all the information we need. If we don't have that, we should instead THROW to let people know what they gave us is ambiguous and might have unintended size effects, so they should handle the normalization themselves because their application will have more context. As an example with what started this discussion, "upcasting" a partial-time to a full-time might lead to nasty clock differences issues when calculating durations etc...

How do we go about fixing this? I think we should first and foremost expand the table I started building, to make sure we have a good understanding among us of what are the known type-representation pairs across languages. This could potentially feed into the documentation of the library later on. And _then_ fix the diverse implementations.

Thoughts?

**Comment by baywet** [comment]
1. this probably be hostile without a major version bump. But it's probably the simplest thing to do. It also brings the question for simpler data types like numbers, etc...
2. randomly adding UTC when we don't know for sure this is the desired behaviour will make for edge cases very hard to troubleshoot (when the service doesn't fail the parsing on its end)
3. probably a lot of work to take on here.

Why would various level of support across languages be dreaded in your opinion?

**Comment by andreaTP** [comment]
> randomly adding UTC

No randomness involved here, we can clearly state that dates will be always normalized to UTC, that's the bottom of it, and it will likely work well enough for most use cases.

> Why would various level of support across languages be dreaded in your opinion?

One of the goals of this repo is to maintain a minimal and portable implementation across languages, introducing exceptions has to be avoided as much as possible as it will make it more difficult to recognize and compare implementations.
I feel strongly about not breaking this rule as much as we can.

> this probably be hostile without a major version bump

I'm considering a 2.0 dropping `Date` support, it has been an exception since the start and I would not be against it.
In Kiota, we agreed on keeping the language specific bits on the abstraction layer, and this goes in that direction.

**Comment by baywet** [comment]
Additional information from @darrelmiller this is not a new problem, it's been long standing in the industry.
https://hudlow.github.io/query-parse-suite/
https://github.com/HTTPWorkshop/workshop2024

**Comment by baywet** [comment]
> 'm considering a 2.0 dropping Date support, it has been an exception since the start and I would not be against it.
In Kiota, we agreed on keeping the language specific bits on the abstraction layer, and this goes in that direction.

From the meeting, we have an agreement on that.

**Comment by andrueastman** [comment]
I believe this can be closed now given the changes made in https://github.com/std-uritemplate/std-uritemplate/issues/242. Yes?

**Comment by andreaTP** [comment]
Right, thanks for the heads up!
